server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      demoApiRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 0
  retry:
    instances:
      demoApiRetry:
        max-attempts: 3
        wait-duration: 500ms
  circuitbreaker:
    instances:
      demoApiCB:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
  timelimiter:
    instances:
      demoApiTimeout:
        timeout-duration: 2s
spring:
  security:
    user:
      name: myuser
      password: mypass